version: "2"
services:
  flask:
    container_name: order-taking
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: order-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: orders
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    ports:
      - "27017:27017"